*** Starting uWSGI 2.0.20 (64bit) on [Tue May  3 08:23:20 2022] ***
compiled with version: 7.5.0 on 22 April 2022 13:27:19
os: Linux-4.4.0-1128-aws #142-Ubuntu SMP Fri Apr 16 12:42:33 UTC 2021
nodename: goorm
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 8
current working directory: /workspace/mbittest
writing pidfile to /workspace/mbittest/tmp/MBIT.pid
detected binary path: /workspace/mbittest/myvenv/bin/uwsgi
chdir() to /workspace/mbittest/
your memory page size is 4096 bytes
detected max file descriptor number: 1024
building mime-types dictionary from file /etc/mime.types...554 entry found
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address /workspace/mbittest/tmp/MBIT.sock fd 3
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.7.4 (default, Nov  4 2020, 10:17:35)  [GCC 7.4.0]
PEP 405 virtualenv detected: /workspace/mbittest/myvenv/
Set PythonHome to /workspace/mbittest/myvenv/
Python main interpreter initialized at 0x557487b92190
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145840 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 2 seconds on interpreter 0x557487b92190 pid: 389 (default app)
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
spawned uWSGI master process (pid: 389)
spawned uWSGI worker 1 (pid: 394, cores: 1)
subprocess 392 exited with code 0
Internal Server Error: /
Traceback (most recent call last):
  File "/workspace/mbittest/myvenv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/workspace/mbittest/myvenv/lib/python3.7/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./main/views.py", line 11, in index
    return render(request, 'main/index.html', context=context)
  File "/workspace/mbittest/myvenv/lib/python3.7/site-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/workspace/mbittest/myvenv/lib/python3.7/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/workspace/mbittest/myvenv/lib/python3.7/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "/workspace/mbittest/myvenv/lib/python3.7/site-packages/django/template/backends/django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/workspace/mbittest/myvenv/lib/python3.7/site-packages/django/template/engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "/workspace/mbittest/myvenv/lib/python3.7/site-packages/django/template/engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "/workspace/mbittest/myvenv/lib/python3.7/site-packages/django/template/loaders/base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/workspace/mbittest/myvenv/lib/python3.7/site-packages/django/template/base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "/workspace/mbittest/myvenv/lib/python3.7/site-packages/django/template/base.py", line 193, in compile_nodelist
    return parser.parse()
  File "/workspace/mbittest/myvenv/lib/python3.7/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/workspace/mbittest/myvenv/lib/python3.7/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/workspace/mbittest/myvenv/lib/python3.7/site-packages/django/template/loader_tags.py", line 278, in do_extends
    nodelist = parser.parse()
  File "/workspace/mbittest/myvenv/lib/python3.7/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/workspace/mbittest/myvenv/lib/python3.7/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/workspace/mbittest/myvenv/lib/python3.7/site-packages/django/template/loader_tags.py", line 222, in do_block
    parser.invalid_block_tag(endblock, 'endblock', acceptable_endblocks)
  File "/workspace/mbittest/myvenv/lib/python3.7/site-packages/django/template/base.py", line 528, in invalid_block_tag
    get_text_list(["'%s'" % p for p in parse_until], 'or'),
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 7: 'endblock', expected 'endblock' or 'endblock head'. Did you forget to register or load this tag?
[pid: 394|app: 0|req: 1/1] 172.17.0.1 () {58 vars in 3484 bytes} [Tue May  3 08:23:22 2022] GET /?t=1651566201913 => generated 149863 bytes in 491 msecs (HTTP/1.1 500) 6 headers in 187 bytes (1 switches on core 0)
Not Found: /favicon.ico
[pid: 394|app: 0|req: 2/2] 172.17.0.1 () {54 vars in 3369 bytes} [Tue May  3 08:23:23 2022] GET /favicon.ico => generated 2809 bytes in 9 msecs (HTTP/1.1 404) 5 headers in 159 bytes (1 switches on core 0)
[pid: 394|app: 0|req: 3/3] 172.17.0.1 () {60 vars in 3515 bytes} [Tue May  3 08:37:37 2022] GET /?t=1651566201913 => generated 2262 bytes in 75 msecs (HTTP/1.1 200) 5 headers in 167 bytes (1 switches on core 0)
...gracefully killing workers...
Gracefully killing worker 1 (pid: 394)...
worker 1 buried after 1 seconds
binary reloading uWSGI...
chdir() to /workspace/mbittest
closing all non-uwsgi socket fds > 2 (max_fd = 1024)...
found fd 3 mapped to socket 0 (/workspace/mbittest/tmp/MBIT.sock)
running /workspace/mbittest/myvenv/bin/uwsgi
[uWSGI] getting INI configuration from /workspace/mbittest/.config/uwsgi/uwsgi.ini
[uwsgi-static] added mapping for /static => /workspace/mbittest/staticfiles/
*** Starting uWSGI 2.0.20 (64bit) on [Tue May  3 08:52:21 2022] ***
compiled with version: 7.5.0 on 22 April 2022 13:27:19
os: Linux-4.4.0-1128-aws #142-Ubuntu SMP Fri Apr 16 12:42:33 UTC 2021
nodename: goorm
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 8
current working directory: /workspace/mbittest
detected binary path: /workspace/mbittest/myvenv/bin/uwsgi
chdir() to /workspace/mbittest/
your memory page size is 4096 bytes
detected max file descriptor number: 1024
building mime-types dictionary from file /etc/mime.types...554 entry found
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 inherited UNIX address /workspace/mbittest/tmp/MBIT.sock fd 3
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.7.4 (default, Nov  4 2020, 10:17:35)  [GCC 7.4.0]
PEP 405 virtualenv detected: /workspace/mbittest/myvenv/
Set PythonHome to /workspace/mbittest/myvenv/
Python main interpreter initialized at 0x55fc0bb35110
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145840 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x55fc0bb35110 pid: 389 (default app)
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
gracefully (RE)spawned uWSGI master process (pid: 389)
spawned uWSGI worker 1 (pid: 397, cores: 1)
subprocess 395 exited with code 0
